quote = {'A hand-breadth from becoming unwound...':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/1/1f/Narration_deathsdoor2.ogg',
'A moment of valor shines brightest against a backdrop of despair.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/2/29/Narration_virtuegeneral.ogg',
'A setback, but not the end of things.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/f/fa/Narration_expeditionfail1.ogg',
'Ambushed by foul invention!':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/b/b6/Narration_trap4.ogg',
'Ancient traps lie in wait, unsprung and thirsting for blood.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/c/ca/Narration_trap5.ogg',
'And now the true test... hold fast, or expire?':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/4/42/Narration_deathsdoor4.ogg',
'And now... the darkness holds dominion – black as death.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/f/f4/Narration_torchzero5.ogg',
'Another life wasted in the pursuit of glory and gold.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/d/d0/Narration_death3.ogg',
'As life ebbs, terrible vistas of emptiness reveal themselves.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/b/b9/Narration_deathsdoor5.ogg',
'As time wore on, her wild policy of self-experimentation grew intolerable. She quaffed all manner of strange fungii, herbs and concoctions, intent on gaining some insight into the horror we both knew to be growing beneath us. The change in her was appalling, and, no longer able to stomach it, I sent her to live in the Weald, where her wildness would be welcomed.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/9/90/Narration_load_weald_03.ogg',
'Beacons in the darkness, stars in the emptiness of the void.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/e/e3/Narration_activateruins2.ogg',
'Cornered! Trapped! And forced to fight on...':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/a/a4/Narration_retreatfail2.ogg',
'Cruel machinations spring to life with a singular purpose!':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/a/a5/Narration_trap1.ogg',
'Curious is the trap-maker\'s art. His efficacy unwitnessed by his own eyes.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/9/9a/Narration_trap2.ogg',
'Darkness closes in, haunting the hearts of men.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/2/29/Narration_torchzero2.ogg',
'Dazed, reeling, about to break...':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/8/80/Narration_crit4.ogg',
'Disinfection, at last.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/f/fd/Narration_activateweald2.ogg',
'Even reanimated bones can fall; even the dead can die again.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/3/36/Narration_bosskillruins1.ogg',
'Even the aged oak will fall to the tempest\'s winds.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/5/5b/Affliction_generic4.ogg',
'Even the cold stone seems bent on preventing passage.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/f/f3/Narration_obstacleruins.ogg',
'Failure tests the mettle of heart, brain, and body.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/e/e2/Narration_expeditionfail4.ogg',
'Fear and frailty finally claim their due.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/4/41/Affliction_fearful.ogg',
'Frustration and fury, more destructive than a hundred cannons.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/f/f5/Affliction_abusive.ogg',
'Gnawing hunger sets in, turning the body against itself, weakening the mind…':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/9/97/Narration_starve1.ogg',
'Good fortune and hard work may yet arrest this plague.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/f/f3/Narration_activateweald1.ogg',
'Ha ha ha! Let those dirty beasts worship the mud now!':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/e/eb/Narration_activatewarrens1.ogg',
'Her knowledge of horticulturalism, and its role in various arcane practices impressed me greatly. My licentious impulse gave way to a genuine, professional respect, and together, we began to plant, harvest, and brew.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/3/33/Narration_load_weald_02.ogg',
'How many rats will it take to gnaw through a tonne of putrid flesh?':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/6/64/Narration_bosskillwarrens1.ogg',
'How quickly the tide turns!':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/d/d4/Narration_crit3.ogg',
'I brought my colleagues back with much of their intellect intact, a remarkable triumph for even the most experienced necromancer. Freed from the trappings of their humanity, they plied their terrible trade anew - the dead reviving the dead, on and on down the years... forever.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/d/d2/Narration_load_crypts_03.ogg',
'I entertained a delegation of experts from overseas, eager to plumb the depths of their knowledge and share with them certain techniques and alchemical processes I had found to yield wondrous and terrifying results. Having learned all I could from my visiting guests, I murdered them as they slept.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/f/fc/Narration_load_crypts_02.ogg',
'I had collected many rare and elusive volumes on ancient herbal properties, and was set to enjoy several weeks immersed in comfortable study. My work was interrupted, however, by a singularly striking young woman who insisted on repeated calls to the house.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/1/11/Narration_load_weald_01.ogg',
'Injury and despondence set the stage for heroism... or cowardice.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/9/9b/Narration_halfstats.ogg',
'It is a travesty - a blundering mountain of hatred and rage.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/6/65/Narration_boss2.ogg',
'Leave her corpse to rot, consumed by the spores she spawned.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/c/c6/Narration_bosskillweald2.ogg',
'Madness, our old friend!':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/5/5a/Affliction_generic5.ogg',
'Mastery over life and death was chief among my early pursuits. I began in humility, but my ambition was limitless. Who could have divined the prophetic import of something as unremarkable as a twitch in the leg of a dead rat?':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/6/6f/Narration_load_crypts_01.ogg',
'Mechanical hazards, possessed by evil intent.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/3/3b/Narration_trap3.ogg',
'More blood soaks the soil, feeding the evil therein.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/b/b8/Narration_death2.ogg',
'More dust, more ashes, more disappointment.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/9/9c/Narration_death6.ogg',
'Mortality clarified in a single strike!':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/8/80/Narration_crit1.ogg',
'My first attempts at summoning were crude and the results, disappointing. I soon found however, that the type and condition of the host\'s meat was a critical factor. The best results came from pigs, whose flesh is most like that of man.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/7/7c/Narration_load_warrens_02.ogg',
'Nature herself - a victim to this spreading corruption: malformed with misintent.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/7/7d/Narration_obstacleweald.ogg',
'No chance for egress - will this be a massacre?':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/3/3d/Narration_retreatfail3.ogg',
'No force of will can overcome a failing body.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/6/66/Narration_starve4.ogg',
'Packs full of steel and war, but nary of thought given to the plow.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/b/ba/Narration_starve3.ogg',
'Perched at the very precipice of oblivion...':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/b/b1/Narration_deathsdoor1.ogg',
'Reeling, gasping, taken over the edge into madness!':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/3/35/Affliction_irrational.ogg',
'Regroup. Reassemble. Evil is timeless, after all.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/3/30/Narration_expeditionfail3.ogg',
'Robbed of their writings, the Swine will grow ever more ignorant - if such a thing were possible.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/d/df/Narration_activatewarrens2.ogg',
'Secrets and wonders can be found in the most tenebrous corners of this place.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/9/9e/Narration_torchzero4.ogg',
'Self-preservation is paramount - at any cost!':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/f/fe/Affliction_selfish.ogg',
'Such a terrible assault cannot be left unanswered!':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/f/f6/Narration_crit5.ogg',
'Such blockages are unsurprising – these tunnels predate even the earliest settlers.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/0/0a/Narration_obstaclewarrens.ogg',
'Survival is a tenuous proposition in this sprawling tomb.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/a/a9/Narration_death1.ogg',
'Teetering on the brink, facing the abyss...':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/e/e9/Narration_deathsdoor3.ogg',
'Terrors may indeed stalk these shadows, but yonder – a glint of gold.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/9/9d/Narration_torchzero3.ogg',
'The darkness holds much worse than mere trickery and bogeymen.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/e/e6/Narration_torchzero1.ogg',
'The Great Thing I had managed to bring through was brutish and stupid. Moreover, it required prodigious amounts of meat to sustain itself, but this was only a trifling concern – after all, I had a village full of it.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/d/d5/Narration_load_warrens_03.ogg',
'The human mind - fragile like a robin\'s egg.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/d/dd/Affliction_generic1.ogg',
'The mind cannot hope to withstand such an assault.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/e/ed/Affliction_generic3.ogg',
'The requirements of survival cannot be met on an empty stomach.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/f/f9/Narration_starve5.ogg',
'The thing is even more horrible in death. Liquefaction cannot come soon enough.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/7/78/Narration_bosskillwarrens2.ogg',
'The walls close in, the shadows whisper of conspiracy!':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/f/f7/Affliction_paranoid.ogg',
'The ways and rituals of blood sacrifice are difficult to master. Those from beyond require a physical vessel if they are to make the crossing into our reality. The timing of the chants is imperative - without the proper utterances at precise intervals, the process can fail spectacularly.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/0/0a/Narration_load_warrens_01.ogg',
'The wood is still poisoned. The way is still blocked. But less people will be eaten.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/2/2f/Narration_bosskillweald1.ogg',
'There can be no hope in this hell, no hope at all.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/5/5c/Affliction_hopeless.ogg',
'This day belongs to the Light!':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/4/41/Narration_activateruins1.ogg',
'This is no place for the weak, or foolhardy.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/3/33/Narration_death5.ogg',
'This is no place for the weak, or the foolhardy.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/5/5b/Narration_death4.ogg',
'Those who covet injury find it in no short supply.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/0/0c/Affliction_masochistic.ogg',
'To fall for such a little thing... a bite of bread...':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/2/2f/Narration_starve2.ogg',
'Towering, fierce, terrible. Nightmare made material!':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/e/e9/Narration_boss1.ogg',
'True desperation is known only when escape is impossible.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/a/a0/Narration_retreatfail1.ogg',
'Twisted and maniacal - a slathering testament to the powers of corruption!':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/8/8a/Narration_boss3.ogg',
'Wherefore, heroism?':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/7/7a/Affliction_generic2.ogg',
'With no living sinew to actuate them, will these walking bones finally fail?':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/e/e2/Narration_bosskillruins2.ogg',
'Without tools of iron, you must rely on flesh and indefatigable purpose.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/3/34/Narration_obstaclenoshovel.ogg',
'Wounds to be tended; lessons to be learned.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/5/5c/Narration_expeditionfail2.ogg',
'You will endure this loss, and learn from it.':'https://darkestdungeon.gamepedia.com/media/darkestdungeon.gamepedia.com/3/3b/Narration_expeditionfail5.ogg'}